language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - postgresql
before_script:
  - psql -c 'create database dbrows;' -U postgres
test:
  - adapter: postgresql
  - database: dbrows_test
  - python setup.py test
env:
  - ROWS_DB_TEST=postgresql://postgres@localhost/dbrows
install:
  - pip install -r .travis.requirements.txt
script: pytest tests