version: '3.4'

services:

  db:
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

  test:
    container_name: test-${DB_ENGINE}-${DB_VERSION}-${PYTHON_VERSION}
    build:
      context: .
      args:
        DB_ENGINE: ${DB_ENGINE}
        PYTHON_VERSION: ${PYTHON_VERSION}
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    links:
      - db

